apiVersion: v1
kind: Pod
metadata:
 name: carlo-uc2-train
spec:
  restartPolicy: Never
  containers:
    - name: train
      image: carlduke/cancer-instance-train:latest
      env:
        - name: WANDB_BASE_URL
          valueFrom:
            secretKeyRef:
              name: carlo-wandbai-auth
              key: host
        - name: WANDB_API_KEY
          valueFrom:
            secretKeyRef:
              name: carlo-wandbai-auth
              key: key
      command: ["wandb", "agent", "carloalbertobarbano/k8s-benchmark/ej9nbb37"]
      resources:
        limits:
          nvidia.com/gpu: 1
        requests:
          nvidia.com/gpu: 1
      volumeMounts:
            - name: cancer-instance
              mountPath: /data
            - name: shm
              mountPath: /dev/shm
  volumes:
      - name: cancer-instance
        persistentVolumeClaim:
          claimName: cancer-instance-dataset
      - name: shm
        emptyDir:
          medium: Memory
