apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: cancer-instance-dataset
spec:
    storageClassName: cdk-cinder
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
          storage: 5Gi