apiVersion: v1
kind: Secret
metadata:
  name: carlo-wandbai-auth
data:
  host: "aHR0cHM6Ly9hcGkud2FuZGIuYWk=" #base64 for "this is a secret"
  key: "MGUyZGJhM2NjYzJlOGNlMDcyMTFhZTY1NDZjOGE4ZGEwOGVjMjhmNw=="